www/portal/urls.py
from django.conf import settings
from django.conf.urls import url
from django.conf.urls import patterns

from .views import *

from . import defaults as defs

urlpatterns = [
    url(
        r'^article/share/(?P<uuid>[-\w]+)$',
        ArticleShareView.as_view(),
        name='article_share_view'
    ),
    url(
        r'^article/(?P<uuid>[-\w]+)/(?P<slug>[-\w]+)$',
        ArticleView.as_view(),
        name='article_view'
    ),
    url(
        r'^site/(?P<slug>[-\w]+)$',
        ArticlePageView.as_view(),
        name='article_page_view'
    ),
    url(
        r'^search$',
        ArticleSearchView.as_view(),
        name='article_search_view'
    ),
    url(
        r'^latest$',
        ArticleLatestView.as_view(),
        name='article_latest_view'
    ),
    url(
        r'^popular$',
        ArticlePopularView.as_view(),
        name='article_popular_view'
    ),
    url(
        r'^featured$',
        ArticleFeaturedView.as_view(),
        name='article_featured_view'
    ),
    url(
        r'^blog$',
        ArticleBlogView.as_view(),
        name='article_blog_view'
    ),
    url(
        r'^approval/request$',
        ApprovalFormView.as_view(),
        name='approval_confirmation_view'
    ),
    url(
        r'^approval/request/sent$',
        ContactMessageSentView.as_view(),
        name='approval_confirmation_sent_view'
    ),
    url(
        r'^$',
        IndexView.as_view(),
        name='index_view'
    ),
]

www/urls.py
from django.conf import settings
from django.contrib import admin
from django.shortcuts import render
from django.conf.urls import patterns
from django.conf.urls import include
from django.conf.urls import url
from django.conf.urls.static import static
from django.views.decorators.csrf import requires_csrf_token
from django.contrib.sitemaps import views as sitemap_views
from django.views.decorators.cache import cache_page
from django.views.generic.base import RedirectView
from django.contrib.staticfiles.storage import staticfiles_storage

from portal import views as pviews
from views import PlainTextView

sitemaps = {
    'site': pviews.StaticViewSitemap,
    'articles': pviews.ArticleSitemap,
    'blogs': pviews.BlogSitemap,
    'pages': pviews.FlatPageSitemap,
}

ADMIN_URI = getattr(settings, 'SITE_ADMIN_URL_PATH', 'admin')
admin.site.site_header = '{} Admin'.format(settings.SITE_NAME)

try:
    favicon = staticfiles_storage.url('img/favicons/favicon.ico')
except ValueError:  # unable to connect to cdn @ this time
    favicon = None

try:
    logo = staticfiles_storage.url('img/logos/logo.png')
except ValueError:  # unable to connect to cdn @ this time
    logo = None

urlpatterns = [
    url(r'^{}/'.format(ADMIN_URI.rstrip('/')), include(admin.site.urls)),
]

# Apps
urlpatterns += [
    url(r'^contact/', include('contactware.urls', namespace='contactware')),

    url(r'^account/user/', include('userware.urls')),
    url(r'^account/user/', include('userware.urls', namespace='userware')),
    url(r'^account/user/', include('profileware.urls', namespace='profileware')),

    url(r'^account/ads/', include('adware.urls', namespace='adware')),

    url(r'^article/', include('articleware.urls', namespace='articleware')),
    url(r'^account/article/', include('articleware.urls', namespace='articleware')),
    url(r'^trac/', include('tracware.urls', namespace='tracware')),
]

urlpatterns += [
    url(r'^sitemap.xml$',
        cache_page(3600)(sitemap_views.index),
        {'sitemaps': sitemaps, 'sitemap_url_name': 'sitemaps'},
    ),

    url(r'^sitemap-(?P<section>.+)\.xml$',
        cache_page(3600)(sitemap_views.sitemap),
        {'sitemaps': sitemaps},
        name='sitemaps'
    ),
]

# Plain Text Views
urlpatterns += [
    url(r'^robots\.txt$', PlainTextView.as_view(template_name='robots.txt')),
    url(r'^crossdomain\.xml$', PlainTextView.as_view(template_name='crossdomain.xml')),
]

if favicon:
    urlpatterns += [
        url(r'^favicon\.ico$', RedirectView.as_view(url=favicon))
    ]
if logo:
    urlpatterns += [
        url(r'^logo\.png$', RedirectView.as_view(url=logo))
    ]

urlpatterns += [
    url(r'^autocomplete/', include('autocomplete_light.urls')),
]

# Rest API Views
if 'rest_framework' in settings.INSTALLED_APPS:
    if 'api_v1' in settings.INSTALLED_APPS:
        urlpatterns += [
            url(r'^api/v1/', include('api_v1.urls', namespace='api_v1')),
        ]

    if 'rest_framework_swagger' in settings.INSTALLED_APPS:
        urlpatterns += [
            url(r'^swagger/', include('rest_framework_swagger.urls', namespace='swagger')),
        ]

    urlpatterns += [
        url(r'^api/auth/', include('rest_framework.urls', namespace='rest_framework')),
        url(r'^api/auth/token/', 'rest_framework.authtoken.views.obtain_auth_token'),
    ]

# Debug static / media
if settings.DEBUG:
    urlpatterns += [
        url(r'^m/(?P<path>.*)$', 'django.views.static.serve', {
            'document_root': settings.MEDIA_ROOT,
        }),
        url(r'^s/(?P<path>.*)$', 'django.views.static.serve', {
            'document_root': settings.STATIC_ROOT,
        }),
    ]

# Social Login
urlpatterns += [
    url('', include('social.apps.django_app.urls', namespace='social')),
]

# Everything else
urlpatterns += [
    url(r'', include('portal.urls', namespace='portal')),
]


@requires_csrf_token
def handler500(request):
    return render(request, '500.html')

www/portal/views/article.py
import json

from django.views.generic import TemplateView
from django.utils.translation import gettext as _
from django.shortcuts import Http404
from django.shortcuts import get_object_or_404
from django.http import HttpResponsePermanentRedirect
from django.contrib import messages
from django.template import RequestContext
from django.template import loader
from django.http import HttpResponse
from django.core.cache import cache

from toolware.utils import mixin
from articleware.models import Article
from articleware.utils import is_user_active

from .. import utils as util
from .. import defaults as defs


class ArticleView(mixin.CsrfProtectMixin, TemplateView):
    """
    Article Object View
    """
    article_flavor = "Article"

    def get_template_names(self):
        template_name = util.get_template_path("article/entry/main.html")
        return template_name

    def get_object(self, queryset=None):
        uuid = self.kwargs['uuid']
        cache_on = not is_user_active(self.request, self.article_flavor)
        if cache_on:
            cache_key = 'article_individual_{}'.format(uuid)
            article = cache.get(cache_key)
            if article:
                return article

        article = get_object_or_404(Article, uuid=uuid)
        if cache_on:
            cache.set(cache_key, article, defs.PORTAL_ARTICLE_SEARCH_CACHE_TIMEOUT_MINUTES)
        return article

    def get_context_data(self, **kwargs):
        user = self.request.user
        context = super(ArticleView, self).get_context_data(**kwargs)
        context['referrer'] = 'latest'
        article = self.get_object()
        context['query_string'] = ''
        if article.is_author(user) or article.is_editor(user):
            article.preview = True
            if article.is_public:
                if article.has_approved_author:
                    msg = _('Your article is public and is viewable to everyone.')
                else:
                    msg = _('Your article is public yet not visible. Get your account approved.')
                messages.add_message(self.request, messages.WARNING, msg)
            elif article.is_unlisted:
                msg = _('Your article is unlisted and can only be viewed by URL.')
                messages.add_message(self.request, messages.WARNING, msg)
            else:
                msg = _('Your article is private and is not viewable by anyone else.')
                messages.add_message(self.request, messages.ERROR, msg)
            context['article'] = article
            return context
        elif article.is_public or article.is_unlisted:
            context['article'] = article
            if article.is_unlisted:
                msg = _('This is an unlisted article, think twice before sharing it with others.')
                messages.add_message(self.request, messages.WARNING, msg)
            return context
        raise Http404

    def get(self, *args, **kwargs):
        obj = self.get_object()
        if self.request.user_agent.is_bot:
            if not obj.is_public:
                raise Http404
        slug = self.kwargs['slug']
        if obj.slug != slug:
            return HttpResponsePermanentRedirect(obj.get_absolute_url())
        return super(ArticleView, self).get(*args, **kwargs)


class ArticlePageView(ArticleView):
    def get_template_names(self):
        template_name = util.get_template_path("article/entry/main.html")
        return template_name

    def get_object(self, queryset=None):
        slug = self.kwargs['slug']
        obj = get_object_or_404(Article, slug=slug)
        return obj

    def get_context_data(self, **kwargs):
        user = self.request.user
        context = super(ArticleView, self).get_context_data(**kwargs)
        article = self.get_object()
        context['query_string'] = ''
        context['article'] = article
        return context


class ArticleShareView(mixin.CsrfProtectMixin, TemplateView):
    """
    Share View
    """
    def get_template_names(self):
        template_name = util.get_template_path("article/misc/share.html")
        return template_name

    def get_context_data(self, **kwargs):
        context = super(ArticleShareView, self).get_context_data(**kwargs)
        self.data = {
            'article': self.get_object()
        }
        context.update(self.data)
        return context

    def get_object(self, queryset=None):
        uuid = self.kwargs['uuid']
        article = get_object_or_404(Article, uuid=uuid)
        return article

www/portal/views/blog.py
from django.core.cache import cache
from django.db.models import Q

from articleware.models import Article
from articleware.utils import is_user_active

from .search import ArticleSearchView
from .. import defaults as defs


class ArticleBlogView(ArticleSearchView):
    """
    Article Blog View
    """
    url_path = 'blog'
    article_flavor = 'Blog'

    def get_data(self):
        data = super(ArticleBlogView, self).get_data()
        data['referrer'] = 'blog'
        return data

    def get_articles_by_search_params(self):
        """
        Returns list of related article based on blog, categories, targets, tags and author.
        """
        cache_on = not is_user_active(self.request, self.article_flavor)
        if cache_on:
            cache_key = self.get_cache_key_for_params_by_type('articles:blog')
            articles = cache.get(cache_key)
            if articles:
                return articles

        text_query = self.get_text_query_list()
        queryset = Article.objects \
            .filter(status=Article.ARTICLE_STATUS_PUBLIC) \
            .filter(flavor=Article.ARTICLE_FLAVOR_BLOG) \
            .filter(text_query)

        for category in self.selected_categories:
            if category:
                queryset = queryset.filter(categories__slug=category)
        for target in self.selected_targets:
            if target:
                queryset = queryset.filter(targets__slug=target)
        for tag in self.selected_tags:
            if tag:
                queryset = queryset.filter(tags__slug=tag)

        if self.selected_author:
            author = self.selected_author[0]
            queryset = queryset.filter(author__username=author)

        articles = queryset.distinct().order_by('-published_at')

        if cache_on:
            cache.set(cache_key, articles, defs.PORTAL_ARTICLE_SEARCH_CACHE_TIMEOUT_MINUTES)

        return articles

www/templates/bs/int/portal/article/format/blog_view.html
{% include "portal/article/format/full_view.html" %}

www/templates/bs/int/portal/article/format/full_view.html
<div class="article-fullview center-block">

  {% if not request.user_agent.is_bot %}
    <div class="hidden">{{request|view_count:article}}</div>
  {% endif %}

  {% if GOOGLE_ADS %}
    {% adsense_info article.author article.track.view as ads_info %}
    {% if ads_info.0 and ads_info.1 %}
        {% include "portal/article/misc/ad_top.html" %}
    {% endif %}
  {% endif %}

  <div class="card-box-content box-shadow-4dp">

    <div class="card-box-header">
      <h1 class="card-box-title top">
        {{article.headline|highlight:query_string}}
      </h1>


      {% if article.author == request.user or article.editor == request.user %}
        <div class="edit-option pull-left">
            {% if article.is_page %}
                <a href="{% url 'articleware:article_page_update' article.id %}" class="confirm" placement="right" title="Edit Page?">
                  <i class="fa fa-pencil text-warning"></i>
                </a>
            {% elif article.is_blog %}
                <a href="{% url 'articleware:article_blog_update' article.id %}" class="confirm" placement="right" title="Edit Blog?">
                  <i class="fa fa-pencil text-warning"></i>
                </a>
            {% else %}
                <a href="{% url 'articleware:article_update' article.id %}" class="confirm" placement="right" title="Edit Article?">
                  <i class="fa fa-pencil text-warning"></i>
                </a>
            {% endif %}
        </div>
      {% endif %}

      <div class="article-author">
        {% if article.author.full_name %}
          <i class='fa fa-user'></i>
          <span class="rotate-wrapper">
            {% author_search_info article.author referrer as author_info %}
            <a href="{{author_info.url}}" rel="index,follow"><span>{{article.author.full_name|highlight:query_string}}</span></a>&nbsp;
            {% if author_info.is_selected %}
              <i class="fa fa-thumb-tack text-danger"></i>
            {% else %}
              <i class="fa fa-thumb-tack text-success fa-rotate-45"></i>
            {% endif %}
          </span>
        {% elif article.preview %}
          <span class="fa text-warning">Warning: Your profile is incomplete. Update your full name to have it shown here.</span>
        {% endif %}

        {% if article.published_at %}
          &nbsp;&nbsp;<i class='fa fa-clock-o'></i>
          <span>
            {% if article.publication_time %}
              {{article.publication_time}}
            {% else %}
              {% if request.user_agent.is_mobile %}
                {{article.published_at|utc|date:"D, d M Y"}} UTC
              {% else %}
                {{article.published_at|utc|date:"l, F d, Y @ f A"}} UTC
              {% endif %}
            {% endif %}
          </span>
          {% endif %}
      </div>

    </div>

    <div class="card-box-body">

    {% for snippet in article.snippets %}
      {% if snippet.type == snippet.SNIPPET_TYPE_TEXT %}

          {% if snippet.content %}
            <div name="#snippet-block-{{snippet.id}}" class="text-content-box">{{snippet.content|securify:request|safe|linebreaksbr}}</div>
          {% elif article.preview %}
            <span class="fa text-warning">Warning: Snippet {{ forloop.counter }} is empty. Add some content or remove it.</span>
          {% endif %}

      {% elif snippet.type == snippet.SNIPPET_TYPE_IMAGE %}

        {% if snippet.images %}
          {% if snippet.images|length == 1 %}
          <div name="#snippet-block-{{snippet.id}}" class="media-container ">
            <div class="image-wrapper">
              <div class="image">
                <img src="{{request|optimized_image:snippet.images.0}}" class="bottom-aligned">
              </div>
            </div>
          </div>
          {% else %}
            {% include "portal/article/carousel/image.html" %}
          {% endif %}
          <div class="media-caption">{% if snippet.caption %}{{snippet.caption|safe}}{% else %} {% endif %}</div>
        {% else %}
          {% if article.preview %}
            <span class="fa text-warning">Warning: Snippet {{ forloop.counter }} is empty. Add images or remove it.</span>
          {% endif %}
        {% endif %}

      {% elif snippet.type == snippet.SNIPPET_TYPE_VIDEO %}

        {% if snippet.videos %}
          {% if snippet.videos|length == 1 %}
          <div name="#snippet-block-{{snippet.id}}" class="media-container">
              <div class="video-wrapper video-play-container">
                <div class="image">
                  <img src="{{snippet.videos.0.image}}" data-link="{{article.primary_video.link}}" class="bottom-aligned">
                  <div class="overlay-play-button" style="background: url('{% static 'img/misc/video-play-button.png' %}') no-repeat;"></div>
                </div>
                <div class="video" data-link="{{snippet.videos.0.link}}"></div>
              </div>
            </div>
          {% else %}
            {% include "portal/article/carousel/video.html" %}
          {% endif %}
          <div class="media-caption">{% if snippet.caption %}{{snippet.caption|safe}}{% else %} {% endif %}</div>
        {% else %}
          {% if article.preview %}
            <span class="fa text-warning">Warning: Snippet {{ forloop.counter }} is empty. Add videos or remove it.</span>
          {% endif %}
        {% endif %}

      {% elif snippet.type == snippet.SNIPPET_TYPE_MAP %}

        {% if snippet.content %}
          <div name="#snippet-block-{{snippet.id}}" class="media-container">
                <div id="map-canvas-{{snippet.id}}" class="flexible-container"></div>
                <script type="text/javascript">
                  document.addEventListener("DOMContentLoaded", function(event) {
                    set_map_params('{{snippet.id|safe}}', '{{snippet.content|safe}}');
                  });
                </script>
            </div>
          <div class="media-caption">{% if snippet.caption %}{{snippet.caption|safe}}{% else %} {% endif %}</div>
        {% else %}
          {% if article.preview %}
            <span class="fa text-warning">Warning: Snippet {{ forloop.counter }} is empty. Add videos or remove it.</span>
          {% endif %}
        {% endif %}

      {% endif %}


      {% if not forloop.last %}<div class="spacer"></div>{% endif %}

    {% endfor %}

    </div>

    <div class="new-divider"></div>
    <div class=center-block>

      <center>
        <div class="article-category-tags">
          {% for category in article.categories.all %}
            {% category_search_info category referrer as cat_info %}
            <a href="{{cat_info.url}}" rel="noindex,follow" type="button" class="btn btn-default rotate-wrapper {% if cat_info.is_selected %} btn-default-selected {% endif %}">
              <span class="category-toggle-button">{{ category.name }}</span>
              {% if cat_info.is_selected %}
                <i class="fa fa-thumb-tack text-danger"></i>
              {% else %}
                <i class="fa fa-thumb-tack text-success fa-rotate-45"></i>
              {% endif %}
            </a>
          {% endfor %}

          {% for tag in article.tags.all %}
            {% tag_search_info tag referrer as tag_info %}
            <a href="{{tag_info.url}}" rel="noindex,follow" type="button" class="btn btn-default rotate-wrapper {% if tag_info.is_selected %} btn-default-selected {% endif %}">
              <span class="tag-toggle-button">{{ tag.name }}</span>
              {% if tag_info.is_selected %}
                <i class="fa fa-thumb-tack text-danger"></i>
              {% else %}
                <i class="fa fa-thumb-tack text-success fa-rotate-45"></i>
              {% endif %}
            </a>
          {% endfor %}

          {% if query_string %}
            <a href="javascript:void(0)" rel="noindex,nofollow" type="button" class="btn btn-default btn-default-selected text-search">
                {{query_string|upper|truncatechars:10}}&nbsp;&nbsp;<i class="fa fa-search-minus text-danger"></i>
            </a>
          {% endif %}
        </div>
      </center>

    </div>


    {% if article.is_public %}
      <div class="article-view-action text-center">

        {% if request.user.is_authenticated and request|is_article_admin %}
          <div data-url="{% url 'articleware:article_featured' article.id %}" class="btn btn-default actionable bold article-featured">
              <i class="fa fa-{% if article.featured %}check-square-o green{% else %}check-square-o black{% endif %}"></i><span class="action-button-text">Featured</span>
          </div>
        {% endif %}

        <div class="btn btn-default viewcount bold">
            <i class="fa fa-eye"></i><span class="action-button-text">{{article.track.view|human_format}}</span>
        </div>


        {% setvar trac_type to 'Like' %}
        {% setvar trac_icon_color to 'green' %}

        {% if request.user.is_authenticated %}
              <a href="{% url 'tracware:tracware_toggler_ajax_url' %}" rel="noindex" {{article|trac_data_tags_initial:trac_type}} class="btn btn-default actionable bold trac_initial_load">
                  <i class="fa fa-heart"></i>
                  <span class="action-button-text trac-togglable-value">{{article.track.like}}</span>
              </a>
        {% else %}
              <a href="{% url 'userware:user_login' %}?next={{request.path}}{% if request.GET.urlencode %}?{{ request.GET.urlencode }}{% endif %}" rel="noindex" class="btn btn-default actionable bold confirm" title="Login to like?" placement="top">
                  <i class="fa fa-heart-o"></i>
                  <span class="action-button-text trac-togglable-value">{{article.track.like}}</span>
              </a>
        {% endif %}


        {% if article.has_approved_author %}
          <a href="#" rel="noindex" class="btn btn-default actionable bold" data-toggle="modal" data-target="#social-sharing-modal-article" data-remote="false" data-url="{% url 'portal:article_share_view' article.uuid %}">
              <i class="fa fa-share-alt"></i><span class="action-button-text">Share</span>
          </a>
        {% else %}
          <a href="#" rel="noindex" class="btn btn-default actionable bold" data-toggle="modal" data-target="#become-an-apporved-author">
              <i class="fa fa-thumbs-o-up"></i><span class="action-button-text">Get Approved</span>
          </a>
        {% endif %}

        {% if not request.user_agent.is_bot %}
          <a href="#" rel="noindex" class="btn btn-default actionable article-history bold hidden">
            <i class="fa fa-arrow-left"></i><span class="action-button-text">Back</span>
          </a>
        {% endif %}

      </div>
    {% endif %}


  </div>

  {% if GOOGLE_ADS %}
    {% adsense_info article.author article.track.view as ads_info %}
    {% if ads_info.0 and ads_info.1 %}
        {% include "portal/article/misc/ad_bottom.html" %}
    {% endif %}
  {% endif %}

  {% if article.is_public and article.has_approved_author %}
    {% include "portal/article/misc/comments.html" %}
  {% endif %}
</div>

www/templates/bs/int/portal/article/format/preview.html
  <div class="card-box-content box-shadow-4dp">

    {% if not request.user_agent.is_bot %}
      <div class="hidden">{{request|hit_count:article}}</div>
    {% endif %}

    {% if article.primary_media %}
      {% if article.primary_media.is_video %}
        <div class="media-container ">
          <div class="video-wrapper video-play-container">
            <div class="image">
              <img src="{{article.primary_media.image}}" data-link="{{article.primary_media.link}}" class="bottom-aligned">
              <div class="overlay-play-button" style="background: url('{% static 'img/misc/video-play-button.png' %}') no-repeat;"></div>
            </div>
            <div class="video" data-link="{{article.primary_media.link}}"></div>
          </div>
        </div>
      {% else %}
        <div class="media-container ">
          <div class="image-wrapper">
            <div class="image">
              <a href="{{article.get_absolute_url}}" rel="index,follow" class="read-full-article">
                <img src="{{request|optimized_image:article.primary_media}}" class="bottom-aligned">
              </a>
            </div>
          </div>
        </div>
      {% endif %}
    {% endif %}

    <h1 class="card-box-title">
        <span class="index-view-headline">{{article.headline|highlight:query_string}}</span>
    </h1>


    {% if article.author == request.user or article.editor == request.user %}
      <div class="edit-option pull-left">
          {% if article.is_page %}
              <a href="{% url 'articleware:article_page_update' article.id %}" class="confirm" placement="right" title="Edit Page?">
                <i class="fa fa-pencil text-warning"></i>
              </a>
          {% elif article.is_blog %}
              <a href="{% url 'articleware:article_blog_update' article.id %}" class="confirm" placement="right" title="Edit Blog?">
                <i class="fa fa-pencil text-warning"></i>
              </a>
          {% else %}
              <a href="{% url 'articleware:article_update' article.id %}" class="confirm" placement="right" title="Edit Article?">
                <i class="fa fa-pencil text-warning"></i>
              </a>
          {% endif %}
      </div>
    {% endif %}

    <div class="article-author">
      {% if article.author.full_name %}
        <i class='fa fa-user'></i>
        <span class="rotate-wrapper">
          {% author_search_info article.author referrer as author_info %}
          <a href="{{author_info.url}}" rel="index,follow"><span>{{article.author.full_name|highlight:query_string}}</span></a>&nbsp;
          {% if author_info.is_selected %}
            <i class="fa fa-thumb-tack text-danger"></i>
          {% else %}
            <i class="fa fa-thumb-tack text-success fa-rotate-45"></i>
          {% endif %}
        </span>
      {% elif article.preview %}
        <span class="fa text-warning">Warning: Your profile is incomplete. Update your full name to have it shown here.</span>
      {% endif %}

      {% if article.published_at %}
        &nbsp;&nbsp;<i class='fa fa-clock-o'></i>
        <span>
          {% if article.publication_time %}
            {{article.publication_time}}
          {% else %}
            {% if request.user_agent.is_mobile %}
              {{article.published_at|utc|date:"D, d M Y"}} UTC
            {% else %}
              {{article.published_at|utc|date:"l, F d, Y @ f A"}} UTC
            {% endif %}
          {% endif %}
        </span>
        {% endif %}
    </div>


    {% if article.primary_content %}
    <div class="card-box-body">
      <div class="text-content-box">
        {% if request.user_agent.is_mobile %}
          {{article.primary_content|textify|truncatechars:200|safe|highlight:query_string}}
        {% else %}
          {{article.primary_content|textify|truncatechars:400|safe|highlight:query_string}}
        {% endif %}
      </div>
    </div>
    {% endif %}

    <div class="new-divider"></div>
    <div class=center-block>

      <center>
        <div class="article-category-tags">
          {% for category in article.categories.all %}
            {% category_search_info category referrer as cat_info %}
            <a href="{{cat_info.url}}" rel="noindex,follow" type="button" class="btn btn-default rotate-wrapper {% if cat_info.is_selected %} btn-default-selected {% endif %}">
              <span class="category-toggle-button">{{ category.name }}</span>
              {% if cat_info.is_selected %}
                <i class="fa fa-thumb-tack text-danger"></i>
              {% else %}
                <i class="fa fa-thumb-tack text-success fa-rotate-45"></i>
              {% endif %}
            </a>
          {% endfor %}

          {% for tag in article.tags.all %}
            {% tag_search_info tag referrer as tag_info %}
            <a href="{{tag_info.url}}" rel="noindex,follow" type="button" class="btn btn-default rotate-wrapper {% if tag_info.is_selected %} btn-default-selected {% endif %}">
              <span class="tag-toggle-button">{{ tag.name }}</span>
              {% if tag_info.is_selected %}
                <i class="fa fa-thumb-tack text-danger"></i>
              {% else %}
                <i class="fa fa-thumb-tack text-success fa-rotate-45"></i>
              {% endif %}
            </a>
          {% endfor %}

          {% if query_string %}
            <a href="javascript:void(0)" rel="noindex,nofollow" type="button" class="btn btn-default btn-default-selected text-search">
                {{query_string|upper|truncatechars:10}}&nbsp;&nbsp;<i class="fa fa-search-minus text-danger"></i>
            </a>
          {% endif %}
        </div>
      </center>

    </div>

    {% if article.is_public %}
    <div class="article-view-action text-center">

      {% if request.user.is_authenticated and request|is_article_admin %}
        <div data-url="{% url 'articleware:article_featured' article.id %}" class="btn btn-default actionable bold article-featured">
            <i class="fa fa-{% if article.featured %}check-square-o green{% else %}check-square-o black{% endif %}"></i><span class="action-button-text">Featured</span>
        </div>
      {% else %}
      <!--   <span class="btn btn-default featured bold">
          <i class="fa {% if article.featured %}fa-star gold{% else %}fa-star-o{% endif %}"></i><span class="action-button-text">Featured</span>
        </span> -->
      {% endif %}

      <div class="btn btn-default viewcount bold">
          <i class="fa fa-eye"></i><span class="action-button-text">{{article.track.view|human_format}}</span>
      </div>


      {% setvar trac_type to 'Like' %}
      {% setvar trac_icon_color to 'green' %}

      {% if request.user.is_authenticated %}
            <a href="{% url 'tracware:tracware_toggler_ajax_url' %}" rel="noindex" {{article|trac_data_tags_initial:trac_type}} class="btn btn-default actionable bold trac_initial_load">
                <i class="fa fa-heart"></i>
                <span class="action-button-text trac-togglable-value">{{article.track.like}}</span>
            </a>
      {% else %}
            <a href="{% url 'userware:user_login' %}?next={{request.path}}{% if request.GET.urlencode %}?{{ request.GET.urlencode }}{% endif %}" rel="noindex" class="btn btn-default actionable bold confirm" title="Login to like?" placement="top">
                <i class="fa fa-heart-o"></i>
                <span class="action-button-text trac-togglable-value">{{article.track.like}}</span>
            </a>
      {% endif %}


      {% if article.has_approved_author %}
        <a href="#" rel="noindex" class="btn btn-default actionable bold" data-toggle="modal" data-target="#social-sharing-modal-article" data-remote="false" data-url="{% url 'portal:article_share_view' article.uuid %}">
            <i class="fa fa-share-alt"></i><span class="action-button-text">Share</span>
        </a>
      {% else %}
        <a href="#" rel="noindex" class="btn btn-default actionable bold" data-toggle="modal" data-target="#become-an-apporved-author">
            <i class="fa fa-thumbs-o-up"></i><span class="action-button-text">Get Approved</span>
        </a>
      {% endif %}

      <a href="{{article.get_absolute_url}}" rel="index,follow" class="btn btn-default actionable read-full-article bold">
          <i class="fa fa-arrow-right"></i><span class="action-button-text">More</span>
      </a>

    </div>
    {% endif %}

  </div>